name: force-remove-cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Short name of cluster INCLUDING unquie id (i.e. ocp-test-01-a4j8a'
        required: true
      region:
        description: 'region in aws'
        required: true
        default: 'us-east-1'

jobs:
  force-remove-openshift-cluster:
    runs-on: macos-latest
    env:
      temp_dir: "temp-${{ github.run_number }}"
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws_region: us-east-1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Download OpenShift installer and update permissions
        shell: bash
        env:
          s3_installer_path: "${{ github.event.inputs.s3_storage }}/macos-installer"
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading OpenShift Installer..."
          aws s3 cp s3://${{ env.s3_installer_path }}/openshift-install ./openshift-install --region us-east-1 --quiet
          echo "Update permissions to executable on the openshift-installer..."
          chmod +rwx ./openshift-install

      - name: Create force retire metadata
        shell: bash
        run: |
          mkdir -p ./${{ env.temp_dir }}
          mkdir -p ./${{ env.temp_dir }}/${{ github.event.inputs.clusterConfigName }}
          export ID=${RANDOM:0:10000}
          export region=${{ github.event.inputs.region }}
          export name=${{ github.event.inputs.clusterName }}
          envsubst < ./destroy-configs/metadata.json > ./${{ env.temp_dir }}/${{ github.event.inputs.clusterConfigName }}/metadata.json

      - name: Destroy cluster
        shell: bash
        run: |
           ./openshift-install destroy cluster --dir=./${{ env.temp_dir }}/${{ github.event.inputs.clusterConfigName }}

