name: remove-cluster

on:
  workflow_dispatch:
    inputs:
      s3_storage:
        description: 'Name AWS S3 storage bucket'
        required: true
        default: 'dina-s3-storage'
      clusterConfigName:
        description: 'Name of cluster config in S3 to pull down and destroy'
        required: true

jobs:
  remove-openshift-cluster:
    runs-on: macos-latest
    env:
      temp_dir: "temp-${{ github.run_number }}"
    steps:
      - name: "Checkout ${{ github.ref }}"
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        env:
          aws_region: us-east-1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Install OpenShift CLI
        uses: redhat-actions/oc-installer@v1

      - name: Download OpenShift installer and update permissions
        shell: bash
        env:
          s3_installer_path: "${{ github.event.inputs.s3_storage }}/macos-installer"
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading OpenShift Installer..."
          aws s3 cp s3://${{ env.s3_installer_path }}/openshift-install ./openshift-install --region us-east-1 --quiet
          echo "Update permissions to executable on the openshift-installer..."
          chmod +rwx ./openshift-install

      - name: Get cluster metadata files from S3
        shell: bash
        run: |
          mkdir -p ./${{ env.temp_dir }}
          echo "Downloading ${{ github.event.inputs.clusterConfigName }} metadata files from S3..."
          aws s3 cp ./${{ env.temp_dir }} s3://${{ github.event.inputs.s3_storage }}/${{ github.event.inputs.clusterConfigName }} --region us-east-1 

      - name: Destroy cluster
        shell: bash
        run: |
           ./openshift-install destroy cluster --dir=./${{ env.temp_dir }}/${{ github.event.inputs.clusterConfigName }}